// This file is generated by `cargo run --manifest-path src-tauri/Cargo.toml --bin generate_desktop_contracts`.
// Do not edit it by hand.

export type StatusCategory = "action" | "info" | "debug" | "error" | "completion" | "warning";

export type FileOperation = "create" | "overwrite" | "replace" | "remove" | "undo";

export type OutputPreview = { content: string, totalLines: number, headDisplayLines: string | null, tailDisplayLines: string | null, fullOutputPath: string | null, };

export type ToolCallDetail = { "kind": "file_read", path: string, startLine: number | null, endLine: number | null, } | { "kind": "file_update", path: string, operation: FileOperation, } | { "kind": "shell", command: string, cwd: string | null, description: string | null, } | { "kind": "search", pattern: string, path: string | null, glob: string | null, fileType: string | null, } | { "kind": "codebase_search", queries: Array<string>, } | { "kind": "fetch", url: string, } | { "kind": "followup", question: string, } | { "kind": "plan", planName: string, } | { "kind": "skill", name: string, } | { "kind": "task", agentId: string, label: string, } | { "kind": "todo_write", count: number, } | { "kind": "todo_read" } | { "kind": "unknown", name: string, };

export type ToolResultDetail = { "kind": "file_diff", path: string, patch: string, } | { "kind": "shell_output", command: string, shell: string, exitCode: number | null, description: string | null, stdout: OutputPreview | null, stderr: OutputPreview | null, } | { "kind": "text", text: string, };

export type FollowupKind = "text" | "single" | "multi";

export type FollowupOption = { id: string, label: string, };

export type FollowupRequest = { followupId: string, workspacePath: string, conversationId: string, requestId: string, kind: FollowupKind, question: string, options: Array<FollowupOption> | null, };

export type FollowupResponse = { followupId: string, cancelled: boolean, text: string | null, selectedOptionIds: Array<string> | null, };

export type SessionMessage = { "kind": "user", id: string, requestId: string, text: string, } | { "kind": "context_compacted", id: string, requestId: string, text: string, } | { "kind": "assistant", id: string, requestId: string, text: string, } | { "kind": "reasoning", id: string, requestId: string, text: string, } | { "kind": "status", id: string, requestId: string, title: string, subtitle: string | null, category: StatusCategory, } | { "kind": "status_output", id: string, requestId: string, text: string, } | { "kind": "tool_start", id: string, requestId: string, name: string, callId: string | null, detail: ToolCallDetail, } | { "kind": "tool_end", id: string, requestId: string, name: string, callId: string | null, summary: string | null, isError: boolean, detail: ToolResultDetail | null, } | { "kind": "error", id: string, requestId: string, message: string, };

export type SessionTodoStatus = "pending" | "in_progress" | "completed" | "cancelled";

export type SessionTodo = { id: string, content: string, status: SessionTodoStatus, };

export type ConversationSessionSummary = { conversationId: string, title: string, updatedAt: string | null, isDraft: boolean, isRunning: boolean, hasPendingFollowup: boolean, };

export type ChatBinding = { workspacePath: string, conversationId: string, };

export type ConversationViewSnapshot = { workspacePath: string, conversationId: string, messages: Array<SessionMessage>, activeRequestIds: Array<string>, requestAgentIds: { [key in string]: string }, todos: Array<SessionTodo>, followup: FollowupRequest | null, ultracodeEnabled: boolean, };

export type WorkspaceKind = "project" | "managed_chat";

export type WorkspaceSession = { kind: WorkspaceKind, workspacePath: string, workspaceName: string, configured: boolean, configurationError: string | null, selectedConversationId: string | null, conversations: Array<ConversationSessionSummary>, };

export type SavedWorkspaceSummary = { id: string, name: string, updatedAt: bigint, };

export type SavedWorkspaceDetail = { id: string, name: string, layoutJson: string, updatedAt: bigint, };

export type SessionSnapshot = { activeWorkspacePath: string | null, activeConversationId: string | null, visibleMessages: Array<SessionMessage>, visibleActiveRequestIds: Array<string>, visibleRequestAgentIds: { [key in string]: string }, visibleTodos: Array<SessionTodo>, visibleFollowup: FollowupRequest | null, visibleUltracodeEnabled: boolean, conversationViews: Array<ConversationViewSnapshot>, uiError: string | null, workspaces: Array<WorkspaceSession>, savedWorkspaces: Array<SavedWorkspaceSummary>, };

export type PromptModelOption = { providerId: string, providerName: string, modelId: string, modelName: string | null, contextLength: bigint | null, supportsReasoning: boolean, reasoningEfforts: Array<string>, };

export type PromptSettings = { availableModels: Array<PromptModelOption>, selectedProviderId: string | null, selectedModelId: string | null, selectedReasoningEffort: string | null, fastEnabled: boolean, };

export type UpdatePromptSettingsInput = { workspacePath: string | null, providerId: string, modelId: string, reasoningEffort: string | null, };

export type ProviderAuthMethodKind = "api_key" | "o_auth_device" | "o_auth_code" | "google_adc" | "aws_profile" | "codex_device" | "codegraff_device" | "kimi_device";

export type ProviderAuthMethod = { kind: ProviderAuthMethodKind, label: string, };

export type ProviderEnvOverride = {
/**
 * The environment variable name (e.g. `OPENAI_API_KEY`).
 */
envKey: string,
/**
 * Shell config file that defines it, if found (e.g. `~/.zshrc`).
 */
filePath: string | null,
/**
 * 1-based line number of the definition, if found.
 */
line: number | null, };

export type ProviderSummary = { id: string, name: string, configured: boolean, authMethods: Array<ProviderAuthMethod>,
/**
 * Set when the provider is configured via an environment variable, so the
 * UI can point at where it's defined (the app can't unset an env var).
 */
envOverride: ProviderEnvOverride | null, };

export type ProviderUrlParam = { name: string, value: string | null, options: Array<string> | null, };

export type ProviderUrlParamValue = { name: string, value: string, };

export type ProviderAuthSessionKind = "api_key" | "device_code" | "cli_login" | "o_auth_code";

export type ProviderAuthSession = { kind: ProviderAuthSessionKind, authSessionId: string, requiresApiKey: boolean, apiKeyHint: string | null, urlParameters: Array<ProviderUrlParam>, verificationUri: string | null, verificationUriComplete: string | null, userCode: string | null, expiresInSeconds: bigint | null, authorizationUrl: string | null, };

export type ProviderOAuthCallback = { authSessionId: string, providerId: string, authorizationCode: string | null, errorMessage: string | null, };

export type StartProviderAuthInput = { workspacePath: string | null, providerId: string, authMethod: ProviderAuthMethodKind, };

export type CompleteProviderAuthInput = { authSessionId: string, apiKey: string | null, authorizationCode: string | null, urlParameters: Array<ProviderUrlParamValue>, };

export type RemoveProviderInput = { workspacePath: string | null, providerId: string, };

export type SendPromptInput = { workspacePath: string, prompt: string, conversationId: string | null, agentId: string | null, };

export type ChatHandoffTarget = "local" | "worktree";

export type HandoffChatInput = { sourceWorkspacePath: string, conversationId: string | null, target: ChatHandoffTarget, branchName: string | null, };

export type RuntimeStatus = { workspacePath: string | null, workspaceName: string | null, gitRepoName: string | null, gitBranchName: string | null, gitBranches: Array<string>, gitWorkspaceKind: GitWorkspaceKind | null, gitMainWorkspacePath: string | null, availableOpenTargets: Array<string>, configured: boolean, configurationError: string | null, };

export type GitWorkspaceKind = "local" | "worktree";

export type CloneRepositoryInput = { repositoryUrl: string, parentDirectory: string, directoryName: string, };

export type QuickStartVisibility = "public" | "private";

export type QuickStartProjectInput = { projectName: string, parentDirectory: string, visibility: QuickStartVisibility, };

export type CheckoutGitBranchInput = { workspacePath: string, branchName: string, };

export type CreateGitBranchInput = { workspacePath: string, branchName: string, };

export type CommitGitChangesInput = { workspacePath: string, message: string, };

export type CreateSavedWorkspaceInput = { chats: Array<ChatBinding>, layoutJson: string, };

export type UpdateSavedWorkspaceLayoutInput = { workspaceId: string, layoutJson: string, };

export type SaveConversationLayoutInput = { conversationId: string, layoutJson: string, };

export type TerminalOpenInput = { terminalId: string, workspacePath: string, cols: number, rows: number, };

export type TerminalWriteInput = { terminalId: string, data: string, };

export type TerminalResizeInput = { terminalId: string, cols: number, rows: number, };

export type TerminalCloseInput = { terminalId: string, };

export type TerminalSession = { terminalId: string, workspacePath: string, shell: string, cols: number, rows: number, };

export type TerminalOutputEvent = { terminalId: string, data: string, };

export type TerminalExitEvent = { terminalId: string, exitCode: number | null, signal: string | null, };

export type TerminalErrorEvent = { terminalId: string, message: string, };

export type CommandKind = "builtin" | "agent" | "workflow";

export type CommandExecutionKind = "runnable" | "modal" | "terminalAssisted" | "unavailable";

export type CommandResultKind = "text" | "snapshot" | "savedFile" | "agents" | "conversations" | "trajectory" | "workspaceStatus" | "workspaceInfo" | "workspaceSearch" | "workspaceSync" | "workflowDraft" | "mcp";

export type CommandDescriptor = {
/**
 * Canonical command name (without the leading slash).
 */
name: string,
/**
 * Short, human-readable usage description.
 */
usage: string,
/**
 * Alternate names that also resolve to this command.
 */
aliases: Array<string>,
/**
 * Origin of the command.
 */
kind: CommandKind,
/**
 * Optional payload: agent id for `Agent`, prompt text for `Workflow`.
 */
value: string | null,
/**
 * True for the agent-switch shorthands (`act`/`plan`/`sage`).
 */
isAgentSwitch: boolean,
/**
 * Execution route the GUI should use for this command.
 */
executionKind: CommandExecutionKind,
/**
 * Whether the command requires an open workspace.
 */
requiresWorkspace: boolean,
/**
 * Whether the command requires an active conversation.
 */
requiresConversation: boolean,
/**
 * Optional argument hint shown in autocomplete and palettes.
 */
argumentHint: string | null,
/**
 * Expected result shape when the command runs.
 */
resultKind: CommandResultKind, };

export type AgentSummary = {
/**
 * Stable agent identifier.
 */
id: string,
/**
 * Human-readable title.
 */
title: string,
/**
 * Human-readable description when configured.
 */
description: string | null,
/**
 * Whether this agent is currently active.
 */
isActive: boolean,
/**
 * Model configured for this agent when resolvable.
 */
modelId: string | null, };

export type AgentsPayload = {
/**
 * Active agent id when one is selected.
 */
activeAgentId: string | null,
/**
 * Selected provider id for the current session.
 */
selectedProviderId: string | null,
/**
 * Selected model id for the current session.
 */
selectedModelId: string | null,
/**
 * Selected reasoning effort for the current model.
 */
selectedReasoningEffort: string | null,
/**
 * Available agents.
 */
agents: Array<AgentSummary>, };

export type ConversationsPayload = {
/**
 * Workspace path the conversations belong to.
 */
workspacePath: string | null,
/**
 * Serialized conversation summaries compatible with existing snapshots.
 */
conversations: Array<ConversationSessionSummary>, };

export type WorkspaceFileStatus = {
/**
 * Relative path.
 */
path: string,
/**
 * Sync status label.
 */
status: string, };

export type WorkspaceStatusPayload = {
/**
 * Workspace path queried.
 */
workspacePath: string,
/**
 * File status entries.
 */
files: Array<WorkspaceFileStatus>, };

export type WorkspaceInfoPayload = {
/**
 * Workspace path queried.
 */
workspacePath: string,
/**
 * Remote workspace id if indexed.
 */
workspaceId: string | null,
/**
 * Indexed working directory if known.
 */
workingDir: string | null,
/**
 * Indexed node count.
 */
nodeCount: bigint | null,
/**
 * Indexed relation count.
 */
relationCount: bigint | null,
/**
 * Last update timestamp as RFC3339 text.
 */
lastUpdated: string | null,
/**
 * Created timestamp as RFC3339 text.
 */
createdAt: string | null, };

export type WorkspaceQueryInput = {
/**
 * Workspace path to query.
 */
workspacePath: string,
/**
 * Semantic query text.
 */
query: string,
/**
 * Search use case for reranking.
 */
useCase: string | null,
/**
 * Maximum number of results.
 */
limit: number | null,
/**
 * Optional path prefix filter.
 */
startsWith: string | null,
/**
 * Optional suffix filters.
 */
endsWith: Array<string> | null, };

export type WorkspaceSearchResult = {
/**
 * Node id returned by the index service.
 */
nodeId: string,
/**
 * Result kind.
 */
kind: string,
/**
 * File path when applicable.
 */
path: string | null,
/**
 * Starting line when applicable.
 */
startLine: number | null,
/**
 * Ending line when applicable.
 */
endLine: number | null,
/**
 * Text preview.
 */
preview: string,
/**
 * Relevance score when returned.
 */
relevance: number | null,
/**
 * Distance score when returned.
 */
distance: number | null, };

export type WorkspaceSearchPayload = {
/**
 * Workspace path queried.
 */
workspacePath: string,
/**
 * Original query.
 */
query: string,
/**
 * Results in backend rank order.
 */
results: Array<WorkspaceSearchResult>, };

export type WorkspaceSyncPayload = {
/**
 * Workspace path synced.
 */
workspacePath: string,
/**
 * Human-readable progress events.
 */
events: Array<string>, };

export type WorkflowDraftInput = {
/**
 * Goal the workflow should accomplish.
 */
goal: string, };

export type WorkflowNode = {
/**
 * Stable node name.
 */
name: string,
/**
 * Worker agent id.
 */
worker: string,
/**
 * Task assigned to the worker.
 */
task: string,
/**
 * Node dependencies.
 */
dependencies: Array<string>,
/**
 * Prior node outputs this node may inspect.
 */
access: Array<string>,
/**
 * Expected artifact.
 */
artifact: string,
/**
 * Stop condition.
 */
stopCondition: string, };

export type WorkflowDraftPayload = {
/**
 * Goal the workflow should accomplish.
 */
goal: string,
/**
 * Compact topology summary.
 */
summary: string,
/**
 * Review nodes.
 */
nodes: Array<WorkflowNode>,
/**
 * Exportable YAML-like representation.
 */
exportText: string,
/**
 * Prompt submitted when the workflow is approved.
 */
approvedPrompt: string,
/**
 * Initial trace lines.
 */
trace: Array<string>, };

export type McpServerSummary = {
/**
 * MCP server name.
 */
name: string,
/**
 * Server transport type.
 */
serverType: string,
/**
 * Command or URL.
 */
target: string,
/**
 * Whether the server is disabled.
 */
isDisabled: boolean,
/**
 * Number of tools currently loaded.
 */
toolCount: number,
/**
 * Tool names currently loaded.
 */
tools: Array<string>,
/**
 * Initialization error when available.
 */
error: string | null,
/**
 * OAuth auth status for HTTP servers when known.
 */
authStatus: string | null, };

export type McpSettingsPayload = {
/**
 * Configured servers.
 */
servers: Array<McpServerSummary>, };

export type McpImportInput = {
/**
 * Configuration scope: `user` or `local`.
 */
scope: string,
/**
 * JSON text containing `mcpServers`.
 */
json: string, };

export type McpServerActionInput = {
/**
 * MCP server name.
 */
name: string,
/**
 * Configuration scope: `user` or `local` when the action edits config.
 */
scope: string | null, };

export type CommandPayload = { "kind": "agents" } & AgentsPayload | { "kind": "conversations" } & ConversationsPayload | { "kind": "workspaceStatus" } & WorkspaceStatusPayload | { "kind": "workspaceInfo" } & WorkspaceInfoPayload | { "kind": "workspaceSearch" } & WorkspaceSearchPayload | { "kind": "workspaceSync" } & WorkspaceSyncPayload | { "kind": "workflowDraft" } & WorkflowDraftPayload | { "kind": "mcp" } & McpSettingsPayload;

export type CommandRunResult = {
/**
 * Heading for the result dialog.
 */
title: string,
/**
 * Informational text to display in a dialog (monospace). `None` when the
 * command mutated state instead of producing output.
 */
body: string | null,
/**
 * A refreshed session snapshot to apply when the command changed state
 * (e.g. compaction, rename).
 */
snapshot: SessionSnapshot | null,
/**
 * A filesystem path the command wrote to (e.g. `/dump`), surfaced to the
 * user so they can locate the output.
 */
savedPath: string | null,
/**
 * High-level result shape.
 */
resultKind: CommandResultKind,
/**
 * Structured payload for first-class GUI surfaces.
 */
payload: CommandPayload | null, };
